### PR TITLE
add nostr

### PR DESCRIPTION
**Pull request by github-tijlxyz**
[nostr](https://github.com/nostr-protocol/nostr) is a protocol that can be used as a social media alternative.This is a proposal for implementing it. 
I can't really use the existing rss/http things since its based on websockets. don't understand the entire codebase yet, so maybe I did something wrong, but this system works quite well.
Just let me know what you think about implementing something like this.

### CODE REVIEW

**Comment by fiatjaf** [comment]
I tested and it works well. I think there is some room for improvements like give out some options about where to link to, for example.

**Comment by alltheseas** [comment]
What's the format for following a npub? 

For instance, https://njump.me/npub123etc ?

**Comment by github-tijlxyz** [comment]
@alltheseas you can just paste in a npub or nprofile. currently it links the posts to njump.me

**Comment by kickscondor** [comment]
Ok heh - I'm so sorry to just get here like a year later. :wave: 

This is an awesome set of changes!! Makes me wonder if I could eventually support other protocols like Gemini or Secure Scuttlebutt or the like.

Unfortunately, this patch belongs in [fraidyscrape](https://github.com/kickscondor/fraidyscrape). All the logic for specific protocols and such needs to go in that library. But this gives me a good foundation for adding it there. (I've created an issue referring back to this [here](https://github.com/kickscondor/fraidyscrape/issues/2).) And, fortunately, anyone who wants this patch now can use your PR.

Very much appreciate this contribution. :pray:

**Pull request closed without merging**
