### PR TITLE
Make tags bar swipeable on mobile

### PR DESCRIPTION
**Pull request by hughwilliams94**
Not entirely sure this interacts that well with the existing buttons. Not actually tested it on a mobile device but it seems to work well enough in the Firefox devtools mobile emulation thingy.

### CODE REVIEW

**Comment by hughwilliams94** [comment]
Built and installed this on Firefox Android and it works like a charm. The only issue could be that `scrollbar-width` is not widely supported in all browsers (Chrome v86+ according to https://css-tricks.com/almanac/properties/s/scrollbar-width/). I don't know if this will be an issue.

**Comment by hughwilliams94** [comment]
I've updated this to use `@supports` so that the changes are only apparent in browsers that support the `scrollbar-width` rule.

**Comment by kickscondor** [comment]
Ok - this is neat. Thank you Hugh! This is a very generous and unexpected surprise.

I will get back to you once I have a chance to try this out further.

**Comment by hughwilliams94** [comment]
Glad you like it, thanks for making such an excellent extension. It is amazingly functional on Firefox Android, which is unusual for extensions!

**Comment by hughwilliams94** [comment]
As I mentioned above, I am not entirely sure it behaves exactly as expected with the existing right and left arrows.

**Pull request merged**
